---
title: "Tadpole occupancy analysis"
Citation: "DiRenzo GV, Che-Castaldo C, Rugenski A, Brenes R, Whiles MR, Pringle CM, Kilham SS, Lips KR (2016) Disassembly of a tadpole community by a multi-host fungal pathogen with limited evidence of recovery. Ecological Applications, online in advance of print. http://dx.doi.org/10.1002/eap.1443"
output: html_document
---

```{r load_packages, include=FALSE}
library(reshape)
library(reshape2)
library(plyr)
library(knitr)
library(rjags)
library(coda)
library(markdown)
options(width=115)
```

```{r global_options, include=FALSE}
opts_chunk$set(
  cache=FALSE, 
  echo=FALSE, 
  warning=FALSE, 
  message=FALSE, 
  tidy.opts=list(blank=FALSE, width.cutoff=100))
```

```{r}
work1 <- read.csv("/Users/Cici/Dropbox/PhD_cope/Chpt1/Chpt 1 June 2016/Tadpole_occ.csv")
  # read in the data

work1$site2 <- as.numeric(as.factor(paste(work1$stream, work1$site)))
  # Give unique identifier to each site-stream combination

work1$year <- gsub("-[0-1][0-9]$", "", work1$date)
  # Isolate the year from the date column

work1$month <- gsub("^200[0-9]-", "", work1$date)
  # Isolate the month from the date column

work1$date2 <- as.Date(paste(work1$month, 1, work1$year,sep = "."), format="%m.%d.%Y")
  # Create formatted date column

work1$bd2 <- as.numeric(as.factor(work1$bd))
  # Post = 1
  # Pre = 2

work1$date2 <- as.numeric(as.factor(work1$date2))
  
work1$stream2 <- as.numeric(as.factor(work1$stream))
  # Cascada = 1
  # Guabal = 2
  # Loop = 3
  # Silenciosa = 4
work1$habitat2 <- as.numeric(as.factor(work1$habitat))
  # isolated pool = 1
  # leafpack = 2
  # riffle = 3
work1$season2 <- as.numeric(as.factor(work1$season))
  # dry = 1
  # wet = 2

work1$species2 <- as.numeric(as.factor(work1$species))
  # Cinguenalis = 1
  # Eprosoblepon = 2
  # Hcolymba= 3
  # Hcolymbiphyllum = 4
  # Hpalmeri = 5
  # Lwarzwitchii = 6
  # Sflotator = 7
  # Snubicola = 8

```

```{r}

# Create vectors made of 1's and 0's for the model to indicate when a covariate is true (= 1) or when it is false (= 0)
isopool <- rep(0,dim(work1)[1]); i <- which(work1$habitat2==1); isopool[i] <- 1
leafpack <- rep(0,dim(work1)[1]); i <- which(work1$habitat2==2); leafpack[i] <- 1
riffle <- rep(0,dim(work1)[1]); i <- which(work1$habitat2==3); riffle[i] <- 1
habitat <- rep(1,dim(work1)[1]); i <- which(work1$habitat2==3); habitat[i] <- 2
bd <- rep(0,dim(work1)[1]); i <- which(work1$bd2==1); bd[i] <- 1

# Isolate the detection/non-detection data
y <- matrix(NA, nrow=dim(work1)[1], 3)
y[,1] <- work1$visit.1
y[,2] <- work1$visit.2
y[,3] <- work1$visit.3

# Bundle data for JAGS
JagsData <- list(
  y = y,
  n = dim(work1)[1],
  sites = 16,
  visits = 3,
  nspecies = 8,
  streams = 4,
  site = work1$site2,
  stream = work1$stream2,
  season = work1$season2-1,  # the -1 makes them 0 or 1
  date = work1$date2,
  ndate = max(work1$date2),
  bd = bd,
  species = work1$species2,
  leafpack = leafpack,
  riffle = riffle,
  habitat = habitat)

```

We make the initial values for each site equal to 1 if tadpole for each species/habitat combination was ever detected there and 0 otherwise. We set site/month combinations that were not surveyed to NA.

``` {r, include=TRUE, echo=TRUE}
{
sink("JagsModel.jags")
cat("

model {
    
# priors
for (i in 1:11) {
  for (j in 1:(nspecies-1)){
    beta[i,j] ~ dnorm(0,.368)
  }
}

for (i in 1:2) {p[i] ~ dunif(0,1)}

for (i in 1:streams) {
  for (j in 1:nspecies) {
    alpha[i,j] ~ dnorm(0,.368)
  }
}

tau ~ dgamma(.01,.01)
sigma <- 1/pow(tau,.5)

tau2 ~ dgamma(.01,.01)
sigma2 <- 1/pow(tau2,.5)


# glass frogs are not found in riffles so set to zero
beta[1,8] ~ dnorm(0,.368)
beta[2,8] ~ dnorm(0,.368)
beta[3,8] <- 0
beta[4,8] ~ dnorm(0,.368)
beta[5,8] <- 0
beta[6,8] ~ dnorm(0,.368)
beta[7,8] ~ dnorm(0,.368)
beta[8,8] ~ dnorm(0,.368)
beta[9,8] <- 0
beta[10,8] ~ dnorm(0,.368)
beta[11,8] <- 0

# likelihood: process model
for (i in 1:sites) {
  for (j in 1:nspecies) {
    gamma[i,j] ~ dnorm(0, tau)
  }
}

for(i in 1:ndate){
  for(j in 1:nspecies){
    eta[i, j] ~ dnorm(0, tau2)
  }
}

for (i in 1:n) {  
    logit(mu[i]) <- alpha[stream[i],species[i]] + beta[1,species[i]]*season[i] + beta[2,species[i]]*leafpack[i] + beta[3,species[i]]*riffle[i] + 
    beta[4,species[i]]*season[i]*leafpack[i] + beta[5,species[i]]*season[i]*riffle[i] + beta[6,species[i]]*bd[i] + beta[7,species[i]]*season[i]*bd[i] +
    beta[8,species[i]]*leafpack[i]*bd[i] + beta[9,species[i]]*riffle[i]*bd[i] + beta[10,species[i]]*season[i]*leafpack[i]*bd[i] + 
    beta[11,species[i]]*season[i]*riffle[i]*bd[i] + gamma[site[i],species[i]] + eta[date[i], species[i]]

    z[i] ~ dbern(mu[i])
}

# likelihood: observation model
for (i in 1:n) {  
  for (v in 1:visits) {  
    muy[i,v] <- z[i]*p[habitat[i]]
    y[i,v] ~ dbern(muy[i,v])
    y.new[i,v] ~ dbern(muy[i,v])
  }
}

# Posterior predictive check of GOF based on detection frequency per year

for (i in 1:n) {
  sum.y[i] <- max(0.01, sum(y[i,]))	
   sum.y.new[i] <- max(0.01, sum(y.new[i,])) 
  eval[i] <- max(0.01, sum(muy[i,])) 
   E[i] <- pow((sum.y[i] - eval[i]),2) / (eval[i] + 0.01) 
  E.new[i] <- pow((sum.y.new[i] - eval[i]),2) / (eval[i] + 0.01)
} #i

fit.act <- sum(E[])
fit.new <- sum(E.new[])

# dervied quantities
# season: 1 = dry, season: 0 = wet

for (i in 1:(nspecies-1)) {
  # pre
  psi[i,1] <- ilogit(mean(alpha[1:4,i])) # isopool, wet
  psi[i,2] <- ilogit(mean(alpha[1:4,i]) + beta[1,i]) # isopool, dry
  psi[i,3] <- ilogit(mean(alpha[1:4,i]) + beta[2,i]) # leafpack, wet
  psi[i,4] <- ilogit(mean(alpha[1:4,i]) + beta[1,i] + beta[2,i] + beta[4,i]) # leafpack, dry
  psi[i,5] <- ilogit(mean(alpha[1:4,i]) + beta[3,i]) # riffle, wet
  psi[i,6] <- ilogit(mean(alpha[1:4,i]) + beta[1,i] + beta[3,i] + beta[5,i]) # riffle, dry

  # post
  psi[i,7] <- ilogit(mean(alpha[1:4,i]) + beta[6,i]) # isopool, wet
  psi[i,8] <- ilogit(mean(alpha[1:4,i]) + beta[1,i] + beta[6,i] + beta[7,i]) # isopool, dry
  psi[i,9] <- ilogit(mean(alpha[1:4,i]) + beta[2,i] + beta[6,i] + beta[8,i]) # leafpack, wet
  psi[i,10] <- ilogit(mean(alpha[1:4,i]) + beta[1,i] + beta[2,i] + beta[4,i] + beta[6,i] + beta[7,i] + beta[8,i] + beta[10,i]) # leafpack, dry
  psi[i,11] <- ilogit(mean(alpha[1:4,i]) + beta[3,i] + beta[6,i] + beta[9,i]) # riffle, wet
  psi[i,12] <- ilogit(mean(alpha[1:4,i]) + beta[1,i] + beta[3,i] + beta[5,i] + beta[6,i] + beta[7,i] + beta[9,i] + beta[11,i]) # riffle, dry
}

  psi[8,1] <- ilogit(mean(alpha[1:4,8])) # isopool, wet
  psi[8,2] <- ilogit(mean(alpha[1:4,8]) + beta[1,8]) # isopool, dry
  psi[8,3] <- ilogit(mean(alpha[1:4,8]) + beta[2,8]) # leafpack, wet
  psi[8,4] <- ilogit(mean(alpha[1:4,8]) + beta[1,8] + beta[2,8] + beta[4,8]) # leafpack, dry
  psi[8,5] <- 0
  psi[8,6] <- 0
  psi[8,7] <- ilogit(mean(alpha[1:4,8]) + beta[6,8]) # isopool, wet
  psi[8,8] <- ilogit(mean(alpha[1:4,8]) + beta[1,8] + beta[6,8] + beta[7,8]) # isopool, dry
  psi[8,9] <- ilogit(mean(alpha[1:4,8]) + beta[2,8] + beta[6,8] + beta[8,8]) # leafpack, wet
  psi[8,10] <- ilogit(mean(alpha[1:4,8]) + beta[1,8] + beta[2,8] + beta[4,8] + beta[6,8] + beta[7,8] + beta[8,8] + beta[10,8]) # leafpack, dry
  psi[8,11] <- 0
  psi[8,12] <- 0

for (i in 1:nspecies) {
  pre[i] <- mean(psi[i,1:6])
  post[i] <- mean(psi[i,7:12])
  delta[i] <-  post[i] - pre[i]/ pre[i]
}

}
",fill = TRUE)
sink()
}
```

```{r tidy=TRUE, echo=TRUE, include=TRUE}
# Set inital values
zst <- apply(y,1,max,na.rm=TRUE)

inits=list(list(z=zst, 
                tau=runif(1,1.1,1.3), 
                tau2=runif(1,1.1,1.3), 
                p = runif(2,.4,.5), 
                alpha = matrix(runif(4*8,-1,1),nrow=4,ncol=8),
                beta = matrix(c(runif(11*7,-1,1),runif(1,-1,1),runif(1,-1,1),NA,runif(1,-1,1),NA,runif(1,-1,1),runif(1,-1,1),runif(1,-1,1),NA,runif(1,-1,1),NA),
                nrow=11,ncol=8), 
                gamma = matrix(runif(16*8,-1,1),nrow=16,ncol=8),
                eta = matrix(runif(25*8,-1,1),nrow=25,ncol=8)),
           list(z=zst, 
                tau=runif(1,1.1,1.3),
                tau2=runif(1,1.1,1.3), 
                p = runif(2,.4,.5), 
                alpha = matrix(runif(4*8,-1,1),nrow=4,ncol=8),
                beta = matrix(c(runif(11*7,-1,1),runif(1,-1,1),runif(1,-1,1),NA,runif(1,-1,1),NA,runif(1,-1,1),runif(1,-1,1),runif(1,-1,1),NA,runif(1,-1,1),NA),
                nrow=11,ncol=8), 
               gamma = matrix(runif(16*8,-1,1),nrow=16,ncol=8),
                eta = matrix(runif(25*8,-1,1),nrow=25,ncol=8)),
          list(z=zst, 
                tau = runif(1,1.1,1.3), 
                tau2=runif(1,1.1,1.3), 
                p = runif(2,.4,.5), 
                alpha = matrix(runif(4*8,-1,1),nrow=4,ncol=8),
                beta = matrix(c(runif(11*7,-1,1),runif(1,-1,1),runif(1,-1,1),NA,runif(1,-1,1),NA,runif(1,-1,1),runif(1,-1,1),runif(1,-1,1),NA,runif(1,-1,1),NA),
                nrow=11,ncol=8), 
               gamma = matrix(runif(16*8,-1,1),nrow=16,ncol=8),
                eta = matrix(runif(25*8,-1,1),nrow=25,ncol=8)))
```

```{r tidy=TRUE, echo=TRUE, include=TRUE}
n.adapt <- 50
n.update <- 80
n.iter <- 10
```

```{r tidy=TRUE, echo=TRUE, include=TRUE}
jm=jags.model("JagsModel.jags", data=JagsData, inits = inits, n.chains=length(inits), n.adapt=n.adapt)
update(jm, n.iter=n.update)
zm = coda.samples(jm, variable.names=c("alpha","beta","gamma","sigma","p","psi","pre","post","delta", "fit.new", "fit.act"), n.iter=n.iter, thin=10)
zm2 = coda.samples(jm, variable.names=c("alpha","beta[1:11,1:7]","beta[1,8]","beta[2,8]","beta[4,8]","beta[6,8]","beta[7,8]","beta[8,8]","beta[10,8]","gamma","sigma","sigma2", "p"), n.iter=n.iter, thin=10)

save(zm, file="PrePostModelsStreamFixed_zm.rda")
save(zm2, file="PrePostModelsStreamFixed_zm2.rda")
```

Here is a summary of the parameter values. Convergence.

```{r tidy=TRUE}
summary(zm)
gelman.diag(zm2)
HPDinterval(zm[[1]], prob=0.95)
```

<center>
```{r fig.width=9, fig.height=8, tidy=TRUE, include=TRUE}
par(mfrow=c(1,1))
plot(zm)
```
</center>

<center>
```{r fig.width=9, fig.height=6, tidy=TRUE, echo=TRUE, eval=TRUE}
#echo=FALSE, eval=FALSE}
fitit <- function(jagsrun){
samples2 = coda.samples(jagsrun, variable.names=c("fit.new","fit.act"), n.iter=n.iter, thin=20)
allchains2 <- rbind(as.matrix(samples2[[1]]), as.matrix(samples2[[2]]), as.matrix(samples2[[3]]))
p2 <- round(mean(allchains2[,1]>allchains2[,2]),2)
m3 <- round_any(min(allchains2[,2],allchains2[,1]), 10, f = floor)
m4 <- round_any(max(allchains2[,2],allchains2[,1]), 10, f = ceiling)
plot(allchains2[,1], allchains2[,2], xlab = expression(T^{obs}), ylab=expression(T^{rep}), cex.lab=1, cex.axis=1, xlim = c(m3,m4), ylim = c(m3,m4), las=1, main = "Modified Pearson Residuals")
abline(0, 1, lwd=2); mtext(p2, side = 3, line = -2, at=(m4-m3)*.1 + m3)
}
fitit(jm)
```
